version: "3.8"

services:
  api-gateway:
    image: "${REGISTRY}/mezanno-api-gateway:${TAG}"
    ports:
      - "8200:80"

  cache:
    image: ${REGISTRY}/mezanno-cache:${TAG}
    volumes:
      - nginx-cache:/var/cache/nginx
    ports:
      - "8201:80"

  layout-worker-wrapper:
    image: ${REGISTRY}/mezanno-layout-worker-wrapper:${TAG}
    ports:
      - "8202:8000"

  layout-worker:
    image: ${REGISTRY}/mezanno-layout-worker:${TAG}
    ports:
      - "8203:8000"
    deploy:
      replicas: 8
      placement:
        constraints:
          - node.role == worker
        max_replicas_per_node: 2

  api-ocr:
    image: ${REGISTRY}/mezanno-api-ocr:${TAG}
    command: ["uv", "run", "main_api_ocr.py"]
    ports:
      - "8204:8000"
    environment:
      - GRADIO_DEBUG=True
      - GRADIO_SERVER_PORT=8000
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_ROOT_PATH=/ocr
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
      - GRADIO_CONCURRENCY_LIMIT=10
    depends_on:
      - rabbitmq

  ocr-worker:
    image: ${REGISTRY}/mezanno-ocr-worker:${TAG}
    command: /bin/sh -c '/app/startup.sh uv run celery --app=worker.celery worker --concurrency=1 -P threads --loglevel=INFO'
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
    volumes:
      - pero-models:/data/pero_ocr
    deploy:
      replicas: 8
      placement:
        constraints:
          - node.role == worker
        max_replicas_per_node: 2

  rabbitmq:
    image: rabbitmq:3.7.8
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  flower:
    image: mher/flower
    ports:
      - "8205:5555"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

volumes:
  nginx-cache:
    driver: local
    driver_opts:
      type: none
      device: /work/mezanno/nginx-cache
      o: bind
  pero-models:
    driver: local
    driver_opts:
      type: none
      device: /work/mezanno/pero-models
      o: bind

