services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: Dockerfile
    ports:
      - "8200:80"
    networks:
      - app-network

  cache:
    build:
      context: cache
      dockerfile: Dockerfile
    volumes:
      - nginx-cache:/var/cache/nginx
    ports:
      - "8201:80"
    networks:
      - app-network

  layout-worker-wrapper:
    build:
      context: layout-worker-wrapper
      dockerfile: Dockerfile
    ports:
      - "8202:8000"
    networks:
      - app-network
  layout-worker:
    build:
      context: layout-worker
      dockerfile: Dockerfile
    ports:
      - "8203:8000"
    networks:
      - app-network


  api-ocr:
    build:
      context: api-ocr
      dockerfile: Dockerfile
    ports:
      - "8204:8000"
    environment:
      - GRADIO_SERVER_PORT=8000
      - GRADIO_SERVER_NAME="0.0.0.0"
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    networks:
      - app-network
    depends_on:
      - rabbitmq


  ocr-worker:
    build:
      context: ocr-worker
      dockerfile: Dockerfile
    command: [celery, --app=worker.celery, worker, --concurrency=1, -P, threads, --loglevel=INFO]
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
    restart: 'no'
    # tmpfs:
    #   - /tmp:size=100M
    volumes:
      - huggingface-cache:/app/.cache/huggingface
      - pero-cache:/app/pero-models



  rabbitmq:
    image: rabbitmq:3.7.8



volumes:
  nginx-cache:
  huggingface-cache:
  pero-cache:

networks:
  app-network:
    driver: bridge