services:
  # api-gateway:
  #   build:
  #     context: api-gateway
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8200:80"

  api-ocr:
    build:
      context: api-ocr
      dockerfile: Dockerfile
    ports:
      - "8204:8000"
    environment:
      - GRADIO_SERVER_PORT=8000
      - GRADIO_SERVER_NAME="0.0.0.0"
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
      # FIXME check this backend works across multiple machines
    depends_on:
      - rabbitmq


  ocr-worker:
    build:
      context: ocr-worker
      dockerfile: test.dockerfile
      # dockerfile: Dockerfile
    command: [celery, --app=worker.celery, worker, --concurrency=1, -P, threads, --loglevel=INFO]
    environment: 
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_RESULT_BACKEND=rpc://
    depends_on:
      - rabbitmq
    # volumes:
      # - pero-cache:/app/pero-models



  rabbitmq:
    image: rabbitmq:3.7.8


## TODO flower

## TODO result backend for celery?


# volumes:
  # pero-cache: