[project]
name = "api-ocr"
version = "0.1.0"
description = "Simple Gradio API"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "celery>=5.5.1",
    "gradio>=5.24.0",
    "pydantic",
]
